# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1
  cypress: cypress-io/cypress@2.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  frontend-build-test:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      # use Node v18.13.0
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install 18.13.0
            nvm alias default 18.13.0

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      # install dependencies for front-end application
      - run:
          name: Front-End Install
          command: |
            npm install
      # build front-end application
      - run:
          name: Front-End Build
          command: |
            npm run build
      - run:
          name: Check browser installation
          command: |
            google-chrome --version
            chromedriver --version
      # run front-end unit tests
      - run:
          name: Front-End Unit Tests
          command: |
            npm run test:unit

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  frontend-build-test-workflow:
    jobs:
      # install Cypress
      - cypress/install:
          name: cypress-install-staging
      - frontend-build-test:
          name: frontend-build-test-unit
          requires:
            - cypress-install-staging
